### ISSUE TITLE
Dynamically Enabling MarkdownEditor does not work. 

### ISSUE THREAD

**Issue by yaplej** [filamentphp/filament#3692] opened 2022-08-26 14:40 UTC
### Package

filament/filament

### Package Version

v2.15.26

### Laravel Version

v9.7.0

### Livewire Version

v2.3

### PHP Version

PHP 8.1.4

### Problem description

When dynamically disabling & enabling a MarkdownEditor the components, buttons, textbox do not become active when its dynamically enabled.

### Expected behavior

It should behave like the RichEditor.

### Steps to reproduce

Make a RichEditor that is enabled & disabled dynamically verify it works.  Change it to a MarkdownEditor.

### Reproduction repository

https://github.com/yaplej/DynamicMarkdownEditor

**Comment by marky291** [comment] 2022-09-06 19:10
@yaplej The link to reproduce does not work

**Comment by yaplej** [comment] 2022-09-07 14:33
@marky291 Its a private repository.

**Comment by ryangjchandler** [comment] 2022-09-07 16:37
@yaplej The reproduction repository needs to be public for us to access it and debug the problem.

**Comment by yaplej** [comment] 2022-09-07 17:49
@ryangjchandler I had already added @marky291 but also went ahead and made it public.

**Comment by marky291** [comment] 2022-09-07 17:53
Can you maybe let us know what file and line to look at? 😂

**Comment by yaplej** [comment] 2022-09-08 13:48
@marky291 Look at the behavior of the Markdown vs Rich editor when they are enabled/disabled.

https://github.com/yaplej/DynamicMarkdownEditor/blob/main/app/Filament/Resources/ChangeRequestResource.php#L44-L60

**Comment by danharrin** [comment] 2022-10-07 09:23
Confirmed, can only fix in v3 when we switch to a different markdown editor though. The reason why this doesn't work is because we need a `wire:ignore` to wrap around the entire editor.

**Comment by danharrin** [comment] 2023-03-19 11:50
Fixed in v3.

**Closed by danharrin** 2023-03-19 11:50 UTC
Labels: bug, confirmed, blocked

**Comment by nlvedwin** [comment] 2023-08-12 02:01
> 

it seems broken again @danharrin for the rich editor markdown works fine tho.

**Comment by danharrin** [comment] 2023-08-12 04:57
I don't think it was ever fixed in the rich editor?
