### ISSUE TITLE
Using disabled and searchable together in Select field causes issue

### ISSUE THREAD

**Issue by ManojKiranAppathurai** [filamentphp/filament#3566] opened 2022-08-19 07:37 UTC
### Package

filament/filament

### Package Version

2.15

### Laravel Version

9.19

### PHP Version

8.1.1

### Problem description

When I use `searchable` in the select filed with `disabled`  state by default and enable it based on other select filed the disabled filed state doesn't change.

However after removing `searchable` fixes the issue

### Expected behavior

The filed should be enabled after selection

### Steps to reproduce

1. Go to user create page
2. Select `Parent Select` from `Filed Set Without Searchable` 
3. You will see `Filed Set Without Searchable -> Child Select` filed will be enabled [Working Fine]
4. Select `Parent Select` from `Filed Set With Searchable` 
5. You will see `Filed Set With Searchable -> Child Select` filed will not be enabled [Issue]

### Reproduction repository

https://github.com/ManojKiranAppathurai/filament-color-picker-issue

**Comment by zepfietje** [comment] 2022-08-19 08:02
Duplicate of https://github.com/filamentphp/filament/issues/3068.

**Closed by zepfietje** 2022-08-19 08:02 UTC
Labels: bug, duplicate, unconfirmed
