### ISSUE TITLE
Configuration file not working !

### ISSUE THREAD

**Issue by Mrsunset9x** [filamentphp/filament#2936] opened 2022-06-27 08:14 UTC
### Package

filament/filament

### Package Version

v2.13.10

### Laravel Version

v9.11

### PHP Version

PHP 8.0.2

### Bug description

I have change the path and namespace of recourses field in your config file. After i ran command make:filament-resource.

All the files still being generated in app folder.

I have read your generation command, you are not using the config for generate folder path

https://github.com/filamentphp/filament/blob/08f614dd6a295bb1711362a009ff9b6d4e7c28bd/packages/admin/src/Commands/MakeResourceCommand.php#L49-L53

Please update this !
Thanks !

**Comment by danharrin** [comment] 2022-06-27 08:20
Duplicate of #2494.

**Closed by danharrin** 2022-06-27 08:20 UTC
Labels: bug, unconfirmed
