### ISSUE TITLE
Livewire::component does not get called on registered resources

### ISSUE THREAD

**Issue by ajnsn** [filamentphp/filament#3283] opened 2022-07-28 20:39 UTC
### Package

filament/filament

### Package Version

v2.15.3

### Laravel Version

v9.22.1

### Livewire Version

v2.10.6

### PHP Version

PHP 8.1.8

### Problem description

I am currently developing an internal plugin for Filament that has resources. In the beginning I registered the resources through the `PluginServiceProvider`, like recommended in the documentation.

Consumers of the plugin will need to override the resources to implement their own logic though, e.g. by extending the plugin resource and putting it in their app's resources folder. 

`FilamentManager` calls `array_unique` within `getResources()` but as the plugin uses it's own namespace, resources will be registered twice as the whole namespace will appear within the `$this->resources` array.

I decided to remove the registration within the `PluginServiceProvider` to let users register the resources on demand within `filament.resources.register`.

This works as expected except now the Livewire component seems to be missing as every page returns a `ComponentNotFoundException`. 

This might be because the `PluginServiceProvider` registers each of the components [by looping through the resources array.](https://github.com/filamentphp/filament/blob/2.x/packages/admin/src/PluginServiceProvider.php#L96-L108) whereas the `FilamentServiceProvider` [only loops](https://github.com/filamentphp/filament/blob/2.x/packages/admin/src/FilamentServiceProvider.php#L119) through the directory defined within the `'filament.livewire.path`.

The registering of the resources is called [somewhere else](https://github.com/filamentphp/filament/blob/2.x/packages/admin/src/FilamentServiceProvider.php#L161).

### Expected behavior

I expected that registering resources with different namespaces than `App\\Filament` (or as defined within `filament.livewire` will work.

### Steps to reproduce

Register a resource within a different namespace via `filament.resources.register` and visit the resource list records page.

### Reproduction repository

-

**Comment by danharrin** [comment] 2022-07-29 08:29
I just tried to reproduce this, and I couldn't. Please create a public GitHub repository to replicate this issue. That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by danharrin** [comment] 2022-07-31 11:39
Ah okay, the reason I couldn't replicate it originally is because I was visiting the List page (as your original post stated this wasnt working), not clicking the Save button on the Edit page.

**Comment by danharrin** [comment] 2022-07-31 12:10
Hello, could you please check if #3324 fixes this issue. Thanks.

**Comment by ajnsn** [comment] 2022-07-31 12:43
Thanks Dan. Yes, that fixes the issue!

Regarding your approach. When I was looking trought the FilamentServiceProvider and PluginServiceProvider, my first idea was to have one place to register resources. Probably mainly the [foreach-loop](https://github.com/filamentphp/filament/blob/2.x/packages/admin/src/PluginServiceProvider.php#L96-L107) within PluginServiceProvider could go somewhere behind the `registerResources` method and every call of this would properly register all the dependent components.

Of course we need to make sure that the original livewire components exclude resource classes.

That was just a rough idea to have a single "API" and maybe this could also work for pages and widgets.

I am not 100% sure if this could work but you could take your time. I think I am on a edge case and already found a solution by just re-binding the pages via the container, which works also for my use case.

Just want to share with you what was my first impression.

**Comment by danharrin** [comment] 2022-07-31 21:35
Hey, taken on your advice and updated the PR. It did turn out to be more code, but it's more optimised now, as we are only looping through the files once.

Could you double check if it all still works?

**Comment by ajnsn** [comment] 2022-07-31 22:08
Thanks Dan, looking good & works here!

**Comment by danharrin** [comment] 2022-08-01 09:37
Great, thanks. Merged.

**Closed** 2022-08-01 09:36 UTC
Labels: bug, cannot reproduce
