### ISSUE TITLE
Error RestoreAction on EditPage

### ISSUE THREAD

**Issue by themahdavi** [filamentphp/filament#2834] opened 2022-06-19 04:18 UTC
### Package

filament/filament

### Package Version

2.13.6

### Laravel Version

9.17

### Livewire Version

2.10

### PHP Version

8.1.5

### Bug description

RestoreAction On Edit Page functionality work and item restored but after click restore modal not close and have this console error
`Uncaught (in promise) DOMException: String contains an invalid character`

**Comment by themahdavi** [comment] 2022-06-21 17:19
how to reproduce this error ?

on table actions and bulk actions work nice but on page action give console error

**Comment by danharrin** [comment] 2022-06-21 19:09
It works fine for me in Chrome and Safari :(

**Comment by themahdavi** [comment] 2022-06-21 19:32
test on chrome : 
![image](https://user-images.githubusercontent.com/31320104/174882819-0acf3ff0-9e8f-4ddb-ad6a-07a04fea94b7.png)

**Comment by themahdavi** [comment] 2022-06-21 20:01
I find problem 
https://github.com/laravel-filament/filament/blob/3b7b71cf95e06ae9c057dc0998ecbe508319f90c/packages/admin/src/Pages/Actions/DeleteAction.php#L35

`$this->keyBindings(['mod+d']);` cause error
when comment this line work fine 

what means mod+d ?
and why on RestoreAction affect from DeleteAction ?

**Comment by themahdavi** [comment] 2022-06-23 16:33
hey @danharrin on new version i am losing RestoreAction on my 2 projects and downgrade version
can you review ` $this->keyBindings(['mod+d']); ` to find solution ?

**Comment by pxlrbt** [comment] 2022-06-30 09:01
Having the same issue: MacOS, Chrome/Safari, latest Filament

> Unhandled Promise Rejection: InvalidCharacterError: The string contains invalid characters.

https://user-images.githubusercontent.com/22632550/176637429-ae329f40-ff00-44fd-85e6-7f800e69bc83.mov

**Comment by pxlrbt** [comment] 2022-06-30 09:07
The issue is the `+` symbol which apparently causes issues on DOM diffing.

**Comment by danharrin** [comment] 2022-06-30 09:32
@pxlrbt is there a list of safe attribute characters anywhere?

**Comment by pxlrbt** [comment] 2022-06-30 09:35
> @pxlrbt is there a list of safe attribute characters anywhere?

@danharrin I was searching for "valid attribute names" but didn't find any. What I tried: `-`, `_`, `.` are good. So maybe underscore or a dash`

**Comment by danharrin** [comment] 2022-07-06 12:11
Fixed by #3039.

**Closed** 2022-07-06 12:10 UTC
Labels: bug, cannot reproduce
