### ISSUE TITLE
Tags disappear when save record and they shown when reload page

### ISSUE THREAD

**Issue by elfeffe** [filamentphp/filament#2867] opened 2022-06-21 11:37 UTC
### Package

filament/spatie-tags-plugin

### Package Version

2

### Laravel Version

v9

### Livewire Version

2

### PHP Version

8.1

### Bug description

When you save the record, the Tags disappear, and they appear again when you refresh the page.

### Steps to reproduce

Just save a record

**Comment by elfeffe** [comment] 2022-06-21 12:40
https://user-images.githubusercontent.com/4717507/174801366-27a73ea3-f8e1-4c9a-9b98-43fee31bc34f.mp4

**Comment by zepfietje** [comment] 2022-07-29 10:42
I can't reproduce this problem, is it still an issue?

If so, can you provide us a reproduction repository URL? That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by zepfietje** [comment] 2022-08-01 15:28
Closing this as inactive and irreproducible.

**Comment by danharrin** [comment] 2022-08-06 22:14
Yes I cannot replicate this, I assume it was fixed by #2999. If it's still an issue in the latest version, please send a bug reproduction repository URL and I will reopen this issue and look into it.

**Closed by danharrin** 2022-08-06 22:14 UTC
Labels: bug, cannot reproduce, needs more info
