### ISSUE TITLE
DateTimePicker inside action modal on EditPage not localized

### ISSUE THREAD

**Issue by yammycode** [filamentphp/filament#3224] opened 2022-07-25 08:30 UTC
### Package

filament/forms

### Package Version

2.14.5

### Laravel Version

9.21.6

### Livewire Version

2.10.6

### PHP Version

8.1

### Problem description

Hello! I have DateTimePicker / DatePicker inside modal action form on EditPage. It has EN language. But my app language is another. And if i add DateTimePicker field on edit page (no modal action) with same settings, i have localized field.

### Expected behavior

Localized DateTimePicker field inside action modal form

### Steps to reproduce

New install. Change app locale. Create some filamentresource. Add action form and add dateTimePicker inside this action on rewsource edit page.

**Comment by danharrin** [comment] 2022-07-25 08:51
Duplicate of #2835.

**Closed by danharrin** 2022-07-25 08:51 UTC
Labels: bug, unconfirmed
