### ISSUE TITLE
When create multi select new option `TypeError: Cannot read properties of null (reading '__livewire')` occur.

### ISSUE THREAD

**Issue by utsavsomaiya** [filamentphp/filament#3707] opened 2022-08-27 11:38 UTC
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v9.26.1

### Livewire Version

v2.10

### PHP Version

PHP 8.1.0

### Problem description

![image](https://user-images.githubusercontent.com/96036522/187027869-56196be0-37a6-475e-a2cd-3c7d53112c3d.png)

Hello!!
I am using the filament admin panel.
When I am using this code :point_down: 
```php
MultiSelect::make('product_name')
       ->relationship('tags', 'tag_name')
       ->createOptionForm([
               TextInput::make('tag_name')
                     ->required()
                     ->rules(['string', 'max:255']),
       ])
      ->required()
```

And here is my repository for my test :
[Reproduce Repository](https://github.com/utsavsomaiya/testing)

### Expected behavior

- I think, you can add the documentation for the `createOptionForm()` method.
- In the edit page retrieve the data then this error does not come!!

### Steps to reproduce

- Check my repository and what is the issue. I don't have any idea about this.

### Reproduction repository

https://github.com/utsavsomaiya/testing

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of null (reading '__livewire')
    at SupportAlpine.js:53:36
    at Object.get (module.esm.js:398:16)
    at Object.get (module.esm.js:308:14)
    at eval (eval at <anonymous> (module.esm.js:471:14), <anonymous>:8:17)
    at module.esm.js:2198:9
(anonymous) @ SupportAlpine.js:53
get @ module.esm.js:398
get @ module.esm.js:308
eval @ VM145:8
(anonymous) @ module.esm.js:2198
```

**Comment by byjujohn** [comment] 2022-08-31 22:24
Same issue referenced here  #3665

**Comment by danharrin** [comment] 2022-09-01 07:39
Duplicate of #3665.

**Closed by danharrin** 2022-09-01 07:39 UTC
Labels: bug, confirmed
