### ISSUE TITLE
Filter PopOver goes off screen in Mobile devices (sm and small under 450px)

### ISSUE THREAD

**Issue by lucidpolygon** [filamentphp/filament#3418] opened 2022-08-07 17:12 UTC
### Package

filament/tables

### Package Version

2.15.3

### Laravel Version

9.22.1

### Livewire Version

2.10

### PHP Version

8.1.4

### Problem description

On mobile screens, the Popover filter div is going off-screen. Most likely caused by the left margin.

### Expected behavior

The popOver filter must not overflow

### Steps to reproduce

1. Attached is a simple project
2. Connect SQLite database
3. Run the project and check the home page in mobile view
4. Try to filter 

### Reproduction repository

https://github.com/lucidpolygon/filament-asda

### Relevant log 
<img width="359" alt="Screen Shot 2022-08-06 at 5 16 43 PM" src="https://user-images.githubusercontent.com/40432572/183302883-b365a300-283f-470b-9321-62e88cf113e2.png">
output

_No response_

**Comment by zepfietje** [comment] 2022-08-19 14:44
This is most probably caused by Alpine Floating UI. I'm reworking dropdowns in #3443 and have briefly looked into this already.

I think we can close this issue, since it will definitely be tested (and thus fixed) before that PR is merged, @danharrin?

**Comment by danharrin** [comment] 2022-08-19 15:57
We'll just link the PR

**Closed** 2022-08-30 21:01 UTC
Labels: bug, confirmed

**Comment by danharrin** [comment] 2022-08-30 21:06
Fixed by #3443
