### ISSUE TITLE
Reactivity issue with Select field with searchable()

### ISSUE THREAD

**Issue by saifulapm** [filamentphp/filament#4329] opened 2022-10-02 22:35 UTC
### Package

filament/forms

### Package Version

v2.16.19

### Laravel Version

v9.33.0

### Livewire Version

Latest

### PHP Version

v8.1.10

### Problem description

Hello, I did try whole day to fix this. I am sure this is a bug. 

```php
Forms\Components\Select::make('client_id')
    ->relationship('client', 'name')
    ->lazy()
    ->searchable(),

Forms\Components\Select::make('staff')
    ->disabled(fn (callable $get) => $get('client_id') === null)
    ->lazy()
    ->searchable()
    ->options(function ($get) {
        $client = Client::find($get('client_id'));
        return $client->getStaff()->limit(50)->pluck('name', 'id');
    }),

```

here `staff` should be enabled on `client` select but staff always staying disabled. If I remove `searchable()` from staff then it working fine.

### Expected behavior

`Staff` should be enabled when I choose client. removing `searchable()` it working well. 

### Steps to reproduce

```php
Forms\Components\Select::make('client_id')
    ->relationship('client', 'name')
    ->lazy()
    ->searchable(),

Forms\Components\Select::make('staff')
    ->disabled(fn (callable $get) => $get('client_id') === null)
    ->lazy()
    ->searchable()
    ->options(function ($get) {
        $client = Client::find($get('client_id'));
        return $client->getStaff()->limit(50)->pluck('name', 'id');
    }),

```

https://user-images.githubusercontent.com/3833316/193479321-4fb4c949-ea0c-413c-8cc5-0d02fe12c28d.mov

### Reproduction repository

https://github.com/saifulapm/filament-issue

**Comment by Z3d0X** [comment] 2022-10-03 02:44
> lazy() doesnt work with our alpine-based components yet

Replace `->lazy()` with `->reactive()`

**Comment by zepfietje** [comment] 2022-10-03 08:59
@ManojKiranAppathurai thanks for commenting.

This is indeed a duplicate of https://github.com/filamentphp/filament/issues/3566 and https://github.com/filamentphp/filament/issues/3068.

As it's hard to come up with a good solution, since it's a limitation with Choices.js, we've closed those issues as not planned.

I do see why you suggest to keep this issue open or pin it.
However, the bug report template also already mentions searching existing issues before opening a new bug report.

[I've clarified this even further to explicitly mention searching closed issues.](https://github.com/filamentphp/filament/pull/4332)
Let's see if that works for now.

**Closed by zepfietje** 2022-10-03 08:59 UTC
Labels: bug, unconfirmed

**Comment by danharrin** [comment] 2022-10-03 09:23
I would suggest using hidden() instead of disabled() which will work dynamically
