### ISSUE TITLE
Disabled on select in repeater not reactive

### ISSUE THREAD

**Issue by Walter-Melon** [filamentphp/filament#3068] opened 2022-07-08 14:48 UTC
### Package

filament/forms

### Package Version

v2.13.24

### Laravel Version

9.11

### PHP Version

8.0.2

### Bug description

With the following form schema when i try to change the disabled state of the itemable_id with the reactive itemable_type field it stays disabled.

Also the repater is empty even with defaultItems(1).

```php
        return [
            Forms\Components\Repeater::make('items')
                ->schema([
                    Forms\Components\Select::make('itemable_type')
                        ->label('Type')
                        ->options([
                            DockerContainerPort::class => 'Container Port'
                        ])
                        ->reactive()
                        ->required()
                        ->afterStateUpdated(fn (callable $set) => $set('itemable_id', null)),
                    Forms\Components\Select::make('itemable_id')
                        ->label('Item')
                        ->required()
                        ->unique(table: Item::class)
                        ->disabled(fn (\Closure $get) => empty($get('itemable_type')))
                        ->searchable()
                        ->getSearchResultsUsing(fn (\Closure $get, string $search) => $this->searchContainerPorts($get('itemable_type'), $search)),
                    Forms\Components\Toggle::make('active')->default(true),
                    Forms\Components\Toggle::make('new_tab'),
                    Forms\Components\Toggle::make('only_admin'),
                ])
                ->defaultItems(1)
                ->disableItemMovement(),
        ];
```

### Reproduction repository

https://github.com/Walter-Melon/filament-select-example

### Steps to reproduce

It appears the disabled closure does not work with searchable select fields.

**Comment by zepfietje** [comment] 2022-07-29 10:50
Can you provide us a reproduction repository URL and then we'll look at your issue?

That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by Walter-Melon** [comment] 2022-08-01 13:57
I did a bid more testing and it appears the disabled closure does not work with searchable select fields.
Here is my testing repository.
https://github.com/Walter-Melon/filament-select-example

**Comment by zepfietje** [comment] 2022-08-11 13:34
This is caused by a bug in Choices.js. I'm working on implementing a workaround.

**Comment by zepfietje** [comment] 2022-08-11 13:58
I'm not sure what's the best way to "watch" the `disabled` state of the element, since Choices.js takes over control after initialization. Any ideas, @danharrin?

**Comment by danharrin** [comment] 2022-08-11 15:25
Here's how we implemented a dynamic min/max for the date picker, using hidden fields. Ugly but works. https://github.com/filamentphp/filament/pull/2314/files#diff-ea8114ac781958e1aea949dc578736fdc36f72f813c7f7395a5fff5a69015f36R36-R37

**Comment by zepfietje** [comment] 2022-08-11 21:09
But how do you watch changes, @danharrin?

**Comment by danharrin** [comment] 2022-08-11 21:21
Maybe x-model and $watch? Not sure if that would work, we might have to close this as Choices doesnt allow it

**Comment by zepfietje** [comment] 2022-08-11 21:50
Hmm, `x-model` probably won't update if Livewire just replaces the value.

We could add a dummy `input` which has the `disabled` attribute and get that value in a `Livewire.hook('element.updating', () => {})` to call `enable()` or `disable()` on the Choices.js component.

**Comment by danharrin** [comment] 2022-08-11 22:02
but then it would call it every time, that sounds inefficient?

**Comment by zepfietje** [comment] 2022-08-12 07:51
We can check the `el` being updated, and only call `disable()` when it equals the input element. Or do you have general concerns that the hook gets called on every Livewire response that updates an element?

**Comment by danharrin** [comment] 2022-08-12 08:58
the latter, general concerns

**Comment by danharrin** [comment] 2022-08-12 14:14
Yeah I agree, its just a limitation with Choices

**Closed** 2022-08-12 14:14 UTC
Labels: bug, confirmed

**Comment by njxqlus** [comment] 2023-11-13 09:10
I used the next hack in my code:
```php
TextInput::make('stand_id_disabled')
    ->readOnly(fn(Get $get) => $get('project_id') === null)
    ->visible(fn(Get $get) => $get('project_id') === null)
    ->label('Stand')
    ->required()
    ->placeholder('Select an option'),

Select::make('stand_id')
    ->relationship('stand', 'name')
    ->required()
    ->searchable()
    ->visible(fn(Get $get) => $get('project_id') !== null)
    ->options(fn(Get $get) => Project::find($get('project_id'))?->stands->pluck('name', 'id'))
    ->preload(),
```

It's not the accurate result but it's possible to create something on this base. Maybe later I'll create a plugin

**Comment by ManuDoni** [comment] 2024-07-03 13:06
This was my solution to this issue, thanks @njxqlus for the base code.
```php
Forms\Components\Select::make('role')
    ->live()
    ->enum(Role::class)
    ->options(Role::class)
    ->afterStateUpdated(fn(Forms\Set $set) => $set('countries', null))
    ->required(),
Forms\Components\Select::make('countries_disabled')
    ->label(__('Managed countries'))
    ->visible(fn(Forms\Get $get) => $get('role') !== Role::CountryManager->value)
    ->disabled()
    ->multiple()
    ->hint(__('This field is only for country managers')),
Forms\Components\Select::make('countries')
    ->label(__('Managed countries'))
    ->visible(fn(Forms\Get $get) => $get('role') === Role::CountryManager->value)
    ->required(fn(Forms\Get $get) => $get('role') === Role::CountryManager->value)
    ->preload()
    ->multiple()
    ->relationship('countries', 'name')
    ->hint(__('This field is only for country managers')),
```

**Comment by Max-Lovell** [comment] 2025-04-25 08:25
A probably easier work-around is to return an empty array for the select options if you don't want any loaded.

```
Select::make('searchable_select')
    ->options(function (Get $get) {
        $accountId = $get('dependent_field');
        if (!$accountId) return [];
        return $account->loadOptions();
    })
    ->searchable()
```

Would be great if you could define the `searchPrompt` or `placeholder` to prompt the user to input into the dependent field  - although I can't get either to reload after the intial state changes. Would help with relatively pain free solution to this problem if it did...
```
->searchPrompt(function(Get $get){
    $accountId = $get('dependent_field');
    if (!$accountId) return 'No account selected';
    return 'Search for...;
})
```
