### ISSUE TITLE
Javascript error occurs after an action that displays a modal is run and the modal closes.

### ISSUE THREAD

**Issue by jojostx** [filamentphp/filament#3665] opened 2022-08-25 07:06 UTC
### Package

filament/filament

### Package Version

^2.13

### Laravel Version

v9.11.0

### Livewire Version

v2.5

### PHP Version

PHP 8.0

### Problem description

After an action that requires confirmation or displays a modal is run, and the modal closes, a javascript error occurs:

`
Alpine: Cannot reference "$wire" outside a Livewire component.
`
`
Uncaught TypeError: wireEl is null
`

### Expected behavior

The action completes and the modal closes without a Javascript error occurring 

### Steps to reproduce

1. Login to Filament admin panel Demo online
2. visit the edit page for any record/row in the brands page
3. eg: [https://demo.filamentphp.com/shop/brands/11/edit?activeRelationManager=0](https://demo.filamentphp.com/shop/brands/11/edit?activeRelationManager=0)
4. delete a related model on the relationship table eg: products relations table.
5. open browser console

- before confirming action:

![Screenshot (33)](https://user-images.githubusercontent.com/42269899/186596963-1e202da1-530b-49f3-9ce8-e302c1227248.png)

- after confirming action:

![Screenshot (32)](https://user-images.githubusercontent.com/42269899/186597527-5b6e414e-8a11-492d-a712-5744a026fa82.png)

### Reproduction repository

https://github.com/jojostx/filament-demo

**Comment by byjujohn** [comment] 2022-08-25 22:29
@jojostx Seems like if you edit a record this occurs too.

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/1469621/186779542-d0993e47-63f2-49ff-83df-3c1786dec006.png">

This is happening on a project I am working on as well, in a similar case where a popup modal is shown on the RelationsManager.

Thanks

**Comment by jojostx** [comment] 2022-08-26 02:57
> @jojostx Seems like if you edit a record this occurs too.
> 
> <img alt="image" width="1679" src="https://user-images.githubusercontent.com/1469621/186779542-d0993e47-63f2-49ff-83df-3c1786dec006.png">
> 
> This is happening on a project I am working on as well, in a similar case where a popup modal is shown on the RelationsManager.
> 
> Thanks

**Comment by jojostx** [comment] 2022-08-26 03:00
@byjujohn I suspect it has to do with the way the modal is closed after an action is dispatch,

**Comment by awcodes** [comment] 2022-09-01 15:17
This looks like a scoping issue or a bug in Alpine.

Apparently, $wire is not defined inside $watch as it is not declared on `this`.

This fixes the issue and I'm happy to do a PR for this, but something doesn't feel right about it. Any thoughts @zepfietje @danharrin 

```js
this.wire = $wire.__instance;
$watch('isOpen', () => {
      if (isOpen) {
          return
      }
      this.wire.mountedTableAction = null
})
```

**Comment by zepfietje** [comment] 2022-09-01 16:19
I've had a similar issue with `$wire` being undefined when closing notifications. That's why I updated that to `Livewire.emit()`.

However, for this case that wouldn't work. Your fix may be kind of a dirty fix, but if it works... Not sure if this issue got introduced just recently and is a regression, or really a bug with Alpine?

**Comment by awcodes** [comment] 2022-09-01 16:49
This has to be something in Alpine. $wire is available outside of $watch.

**Comment by zepfietje** [comment] 2022-09-01 16:50
@danharrin mentioned he had a potential fix ready locally. Let's see what he'll PR.

**Comment by danharrin** [comment] 2022-09-01 17:13
@awcodes I submitted PR #3810 which completely removes that code. It was originally added to allow people to customize their action forms based on Create or Edit, but it never worked properly as some actions use `mountedAction` and some use `mountedTableAction`. I don't see any reason for people to manually check the `$this->mountedAction` when we have `$context` now.

**Comment by danharrin** [comment] 2022-09-01 17:18
But potentially it is a breaking change if we remove it...

**Comment by awcodes** [comment] 2022-09-01 18:47
So, we're good on this?

**Comment by danharrin** [comment] 2022-09-01 18:48
Is it a Livewire bug that `$wire` doesnt work inside watchers?

**Comment by awcodes** [comment] 2022-09-01 19:15
Hard to say. The error is getting thrown by SupportAlpine.js which is in livewire, but the fact that $wire is always null inside $watch could be an Alpine bug.

![Screen Shot 2022-09-01 at 3 14 17 PM](https://user-images.githubusercontent.com/3596800/187994355-c2864a4a-b108-4a1a-b529-9e2d0862ae3c.png)

**Comment by danharrin** [comment] 2022-09-01 19:37
Does `this.wire = $wire` in your fix not work? Does setting a property on the instance really reflect that change in the backend using an AJAX request?

**Comment by awcodes** [comment] 2022-09-01 19:45
`this.wire = $wire` works, it stops the error from happing. Just a really gross way of doing it, IMO.

**Comment by danharrin** [comment] 2022-09-01 20:12
But does it make an AJAX request with your fix?

**Comment by awcodes** [comment] 2022-09-01 20:18
I'm seeing the same AJAX requests with or without the fix

**Comment by danharrin** [comment] 2022-09-01 20:48
weird... so the console error is there for nothing?

**Comment by awcodes** [comment] 2022-09-01 20:51
Looks like it. LOL

**Comment by zepfietje** [comment] 2022-09-01 21:05
> Looks like it. LOL
> 
> Maybe it's some weird race condition.

Had the same with notifications. Worked fine despite the error.

**Comment by danharrin** [comment] 2022-09-01 21:06
And did you fix that?

**Comment by zepfietje** [comment] 2022-09-01 21:10
> And did you fix that?

https://github.com/filamentphp/filament/issues/3665#issuecomment-1234502935

I first solved that case by passing `$wire` into the JS file instead of accessing `this.$wire`. That seemed to fix it. Later converted `$wire.emit()` to `Livewire.emit()` which I found cleaner. Unfortunately, that won't work for this exact issue, as you need to call a method on the right Livewire instance.

**Comment by danharrin** [comment] 2022-09-01 21:11
Alright. I am going to update my PR to @awcodes's suggestion

**Comment by zepfietje** [comment] 2022-09-01 21:12
Seems a good solution for now.

**Comment by danharrin** [comment] 2022-09-01 21:20
Turns out that setting `__instance.property` doesnt make an AJAX request, so the solution doesn't work.

I swapped it out for `__instance.set('property', null)` which works fine

**Closed** 2022-09-01 21:21 UTC
Labels: bug, confirmed

**Comment by bokoch** [comment] 2022-09-18 21:06
@danharrin Any news regarding this issue? I see it still reproduced and looks like fix was reverted.

**Comment by danharrin** [comment] 2022-09-19 08:59
Hey, the fix was not reverted, we just didn't need any of the code that handled closing modals any more. I can't reproduce the problem myself any more? Please submit a new issue with a reproduction repository.

**Comment by bokoch** [comment] 2022-09-19 09:01
Ok, thanks. I think similar issue already created here https://github.com/filamentphp/filament/issues/3906
