### ISSUE TITLE
DatePicker locale in modals

### ISSUE THREAD

**Issue by invaders-xx** [filamentphp/filament#2970] opened 2022-06-29 12:33 UTC
### Package

filament/filament

### Package Version

v2.13.12

### Laravel Version

v9.19.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8

### Bug description

When using a DatePicker in a modal, the dayjs locale file never gets pulled.

**Comment by danharrin** [comment] 2022-06-29 12:35
Duplicate of #2835.

**Closed** 2022-06-29 12:36 UTC
Labels: bug, unconfirmed
