### ISSUE TITLE
Issues with fileupload form widgets

### ISSUE THREAD

**Issue by SebastiaanKloos** [filamentphp/filament#2957] opened 2022-06-28 14:11 UTC
### Package

filament/forms

### Package Version

v2.13.9

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.0

### Bug description

When trying to delete a file and then save, I get an error.

Flare link:
https://flareapp.io/share/xPQkn2y5#F77

### This flow breaks
1. Upload image to `SpatieMediaLibraryFileUpload` and `FileUpload`
2. Remove the file in `SpatieMediaLibraryFileUpload` and save the form
3. Without reloading the page, upload a file with `SpatieMediaLibraryFileUpload`
4. Click save, and boom it crashes 💣

```php
->schema([
	SpatieMediaLibraryFileUpload::make('image')
	  	->collection('image')
	 	->label('Image'),
	HasManyRepeater::make('blocks')
		->relationship('blocks')
		->schema([
			FileUpload::make('config.file')
				->label('Image'),
		]),
]);
```

### This flow works
1. Upload image to `SpatieMediaLibraryFileUpload` and `FileUpload`
2. Remove the file in `SpatieMediaLibraryFileUpload` and save the form
3. ***Reload the page***
4. Upload a file with `SpatieMediaLibraryFileUpload`
5. Click save

**Comment by zepfietje** [comment] 2022-07-29 10:46
Can you provide us a reproduction repository URL and then we'll look at your issue?

That would allow us to download it and review your bug much easier, so it can be fixed quicker. Please make sure to give us some instructions on where to find the bug, and include a database seeder with everything we need to set it up quickly.

**Comment by SebastiaanKloos** [comment] 2022-08-11 13:06
@zepfietje it's fixed. However there is a new bug. When uploading a file. Then without saving remove it. Then clicking save. The file is still there

**Comment by zepfietje** [comment] 2022-08-11 13:16
> @zepfietje it's fixed. However there is a new bug. When uploading a file. Then without saving remove it. Then clicking save. The file is still there. When I'm back from my holiday, I'll submit a repo

That's a duplicate of https://github.com/filamentphp/filament/issues/3191.

Closing this issue, since you mentioned it's fixed.

**Closed by zepfietje** 2022-08-11 13:16 UTC
Labels: bug, needs more info, unconfirmed
