### ISSUE TITLE
MultiSelect disabled() is not "dynamic"

### ISSUE THREAD

**Issue by tiagof** [filamentphp/filament#3785] opened 2022-08-31 13:35 UTC
### Package

filament/forms

### Package Version

v2.15.20

### Laravel Version

v9.25.1

### PHP Version

PHP 8.1

### Problem description

MultiSelect `->disabled()` does not work as expected when a closure is passed to determine its disabled status.

### Expected behaviour

The same behaviour as the non-multiple `Select`

### Steps to reproduce

Create this form:

```php
public static function form(Form $form): Form
{
    return $form
        ->columns(1)
        ->schema([
            Forms\Components\TextInput::make('name')
                ->reactive(),

            Forms\Components\MultiSelect::make('select With problem')
                ->options([
                    'a' => 'A',
                    'b' => 'B',
                ])
                // this DOESN'T work
                ->disabled(fn (callable $get) => strlen($get('name')) % 2),

            Forms\Components\Select::make('select ok')
                ->options([
                    'a' => 'A',
                    'b' => 'B',
                ])
                // this DOES
                ->disabled(fn (callable $get) => strlen($get('name')) % 2),
        ]);
}
```

go to the page and start typing in the `name` input. With an even number of chars types, both `selects` should be disabled, which is not happening.

This is (almost for sure) due to the `wire:ignore` on line 97 of the `select.blade.php` file ... but not sure how to fix it.

### Reproduction repository

https://github.com/tiagof/filament-bug-reports/tree/bug/select-multiple-disabled-not-dynamic

**Comment by zepfietje** [comment] 2022-08-31 13:42
Duplicate of https://github.com/filamentphp/filament/issues/3068 and https://github.com/filamentphp/filament/issues/3566.

**Closed** 2022-08-31 13:43 UTC
Labels: bug, unconfirmed
